export const tutoringSubjects = [
  { slug: 'accounting', name: 'Accounting', description: 'financial accounting, managerial accounting, journal entries, and exam review' },
  { slug: 'finance', name: 'Finance', description: 'corporate finance, investments, valuation, Excel models, and problem sets' },
  { slug: 'economics', name: 'Economics', description: 'microeconomics, macroeconomics, graphs, models, and quantitative reasoning' },
  { slug: 'biology', name: 'Biology', description: 'cell biology, genetics, lab concepts, and pre-health coursework' },
  { slug: 'chemistry', name: 'Chemistry', description: 'general chemistry, organic chemistry, reactions, labs, and exam prep' },
  { slug: 'physics', name: 'Physics', description: 'mechanics, electricity and magnetism, formulas, and problem solving' },
  { slug: 'calculus', name: 'Calculus', description: 'limits, derivatives, integrals, series, and applied problem solving' },
  { slug: 'statistics', name: 'Statistics', description: 'probability, inference, regressions, data analysis, and exams' },
  { slug: 'computer-science', name: 'Computer Science', description: 'programming, data structures, algorithms, debugging, and projects' },
  { slug: 'writing', name: 'Writing', description: 'essays, research papers, outlines, citations, and writing assignments' },
  { slug: 'exam-prep', name: 'Exam prep', description: 'midterm prep, final exam review, quizzes, and cumulative study plans' },
];

export const schoolSeoSubjects = [
  {
    slug: 'biology-tutors',
    shortSlug: 'biology',
    category: 'STEM',
    name: 'Biology',
    titleSubject: 'Biology Tutors',
    searchTerm: 'Biology',
    description: 'cell biology, genetics, molecular biology, physiology, lab concepts, and pre-health exam prep',
    keywords: ['biology tutor', 'college biology tutoring', 'cell biology tutor', 'genetics tutor', 'pre med biology tutor'],
    painPoints: ['dense memorization', 'diagram-heavy exams', 'lab reports', 'pre-health pressure'],
    relatedSubjects: ['chemistry-tutors', 'organic-chemistry-tutors', 'statistics-tutors', 'psychology-tutors'],
    tutoringCopy: 'Biology tutoring helps students organize large amounts of information and connect vocabulary to systems, diagrams, experiments, and exam questions. Ask Marketplace supports help with cell biology, genetics, molecular biology, physiology, lab concepts, and pre-health review.',
    painPointCopy: 'Biology courses can feel overwhelming because students have to memorize details while also understanding processes. A tutor can help turn notes, slides, and practice questions into a study plan that is easier to repeat.',
    faqs: [
      ['What can a biology tutor help with?', 'A biology tutor can help with cell structure, genetics, molecular biology, physiology, lab concepts, diagrams, terminology, and exam prep.'],
      ['Is biology tutoring useful for pre-med students?', 'Yes. Pre-health students often use biology tutoring to stay consistent in prerequisite courses and prepare for high-pressure exams.'],
      ['Can biology tutoring help with lab reports?', 'Tutors can help students understand lab concepts, organize results, and improve the clarity of their explanations while keeping the work their own.'],
    ],
  },
  {
    slug: 'chemistry-tutors',
    shortSlug: 'chemistry',
    category: 'STEM',
    name: 'Chemistry',
    titleSubject: 'Chemistry Tutors',
    searchTerm: 'Chemistry',
    description: 'general chemistry, stoichiometry, equilibrium, thermodynamics, acids and bases, labs, and exams',
    keywords: ['chemistry tutor', 'college chemistry tutoring', 'general chemistry tutor', 'chemistry exam prep', 'chemistry homework help'],
    painPoints: ['multi-step calculations', 'lab concepts', 'equation setup', 'fast cumulative exams'],
    relatedSubjects: ['biology-tutors', 'organic-chemistry-tutors', 'physics-tutors', 'calculus-tutors'],
    tutoringCopy: 'Chemistry tutoring helps students practice the setup behind each problem instead of guessing which formula to use. Ask Marketplace supports general chemistry, stoichiometry, equilibrium, thermodynamics, acids and bases, lab review, and exam prep.',
    painPointCopy: 'Chemistry often combines concepts, algebra, units, and lab reasoning in the same assignment. A tutor can help students slow down the setup and build confidence with repeatable problem-solving patterns.',
    faqs: [
      ['What topics can a chemistry tutor cover?', 'Chemistry tutors can help with stoichiometry, bonding, equilibrium, thermodynamics, kinetics, acids and bases, lab concepts, and exam review.'],
      ['Can tutoring help with general chemistry?', 'Yes. General chemistry is a common tutoring subject because it moves quickly and becomes cumulative fast.'],
      ['Can chemistry tutors help before exams?', 'Yes. Tutors can review weak topics, walk through representative problems, and help students prioritize practice.'],
    ],
  },
  {
    slug: 'organic-chemistry-tutors',
    shortSlug: 'organic-chemistry',
    category: 'STEM',
    name: 'Organic Chemistry',
    titleSubject: 'Organic Chemistry Tutors',
    searchTerm: 'Organic Chemistry',
    description: 'reaction mechanisms, synthesis, stereochemistry, spectroscopy, functional groups, and orgo exam prep',
    keywords: ['organic chemistry tutor', 'orgo tutor', 'college organic chemistry tutoring', 'reaction mechanisms tutor', 'organic chemistry exam prep'],
    painPoints: ['mechanism memorization', 'synthesis planning', 'stereochemistry', 'high-stakes exams'],
    relatedSubjects: ['chemistry-tutors', 'biology-tutors', 'physics-tutors', 'calculus-tutors'],
    tutoringCopy: 'Organic chemistry tutoring helps students move from memorizing reactions to understanding patterns. Ask Marketplace supports mechanisms, synthesis, stereochemistry, spectroscopy, functional groups, and orgo exam preparation.',
    painPointCopy: 'Organic chemistry can punish shallow memorization because exam questions often twist familiar reactions. A tutor can help students recognize patterns and practice the reasoning behind each step.',
    faqs: [
      ['What can an organic chemistry tutor help with?', 'Organic chemistry tutors can help with mechanisms, synthesis, stereochemistry, spectroscopy, functional groups, nomenclature, and exam review.'],
      ['Is organic chemistry tutoring useful for pre-med students?', 'Yes. Many pre-health students use orgo tutoring because the course is demanding and often central to their academic plans.'],
      ['Can tutoring help with reaction mechanisms?', 'Yes. Tutors can help students understand electron movement, reaction conditions, and the logic behind mechanism steps.'],
    ],
  },
  {
    slug: 'physics-tutors',
    shortSlug: 'physics',
    category: 'STEM',
    name: 'Physics',
    titleSubject: 'Physics Tutors',
    searchTerm: 'Physics',
    description: 'mechanics, electricity and magnetism, waves, circuits, formulas, diagrams, and problem solving',
    keywords: ['physics tutor', 'college physics tutoring', 'mechanics tutor', 'electricity and magnetism tutor', 'physics exam prep'],
    painPoints: ['word problems', 'free-body diagrams', 'formula selection', 'calculus-based reasoning'],
    relatedSubjects: ['calculus-tutors', 'engineering-tutors', 'chemistry-tutors', 'statistics-tutors'],
    tutoringCopy: 'Physics tutoring helps students translate word problems into diagrams, equations, and clear reasoning. Ask Marketplace supports mechanics, electricity and magnetism, waves, circuits, formulas, and exam prep.',
    painPointCopy: 'Physics can be difficult because the first step is often deciding what the problem is really asking. A tutor can help students practice modeling, formula choice, and checking whether an answer makes sense.',
    faqs: [
      ['What can a physics tutor help with?', 'Physics tutors can help with mechanics, forces, energy, momentum, electricity and magnetism, circuits, waves, diagrams, and exam practice.'],
      ['Can physics tutoring help with word problems?', 'Yes. Tutors can help students translate word problems into diagrams, known variables, equations, and a clear solve path.'],
      ['Is calculus-based physics supported?', 'Yes. Students can look for tutors who are comfortable with calculus-based physics and related math.'],
    ],
  },
  {
    slug: 'calculus-tutors',
    shortSlug: 'calculus',
    category: 'STEM',
    name: 'Calculus',
    titleSubject: 'Calculus Tutors',
    searchTerm: 'Calculus',
    description: 'limits, derivatives, integrals, optimization, series, multivariable calculus, and exam prep',
    keywords: ['calculus tutor', 'college calculus tutoring', 'Calc I tutor', 'Calc II tutor', 'multivariable calculus tutor'],
    painPoints: ['abstract concepts', 'algebra mistakes', 'proof-style reasoning', 'cumulative exams'],
    relatedSubjects: ['physics-tutors', 'statistics-tutors', 'engineering-tutors', 'computer-science-tutors'],
    tutoringCopy: 'Calculus tutoring helps students understand the concept behind each technique and then practice enough to use it under exam pressure. Ask Marketplace supports limits, derivatives, integrals, optimization, series, multivariable calculus, and review for quizzes and finals.',
    painPointCopy: 'Calculus problems often go wrong because of small algebra gaps or unclear setup. A tutor can help students identify the right method, practice clean work, and understand why the method applies.',
    faqs: [
      ['What calculus courses can tutors help with?', 'Calculus tutors can help with Calc I, Calc II, multivariable calculus, limits, derivatives, integrals, series, and applications.'],
      ['Can calculus tutoring help with physics or engineering?', 'Yes. Calculus support is often useful for physics, engineering, economics, data science, and other quantitative courses.'],
      ['Can I get help before a calculus exam?', 'Yes. Tutors can help students review methods, practice representative problems, and organize formulas and concepts.'],
    ],
  },
  {
    slug: 'statistics-tutors',
    shortSlug: 'statistics',
    category: 'STEM',
    name: 'Statistics',
    titleSubject: 'Statistics Tutors',
    searchTerm: 'Statistics',
    description: 'probability, hypothesis testing, confidence intervals, regression, data analysis, and statistical software',
    keywords: ['statistics tutor', 'college statistics tutoring', 'probability tutor', 'regression tutor', 'stats exam prep'],
    painPoints: ['wording-heavy questions', 'software output', 'formula choice', 'interpreting results'],
    relatedSubjects: ['data-science-tutors', 'psychology-tutors', 'economics-tutors', 'calculus-tutors'],
    tutoringCopy: 'Statistics tutoring helps students connect formulas, software output, and plain-English interpretation. Ask Marketplace supports probability, hypothesis testing, confidence intervals, regression, data analysis, and exam prep.',
    painPointCopy: 'Statistics is hard when students can calculate an answer but do not know what it means. A tutor can help with setup, interpretation, and the language professors expect in written answers.',
    faqs: [
      ['What can a statistics tutor help with?', 'Statistics tutors can help with probability, distributions, hypothesis tests, confidence intervals, regression, data analysis, and interpretation.'],
      ['Can statistics tutoring help with software?', 'Yes. Tutors may support Excel, R, Python, SPSS, or course-specific tools depending on their background.'],
      ['Is statistics tutoring useful outside STEM?', 'Yes. Statistics is common in psychology, economics, business, political science, public health, and social science courses.'],
    ],
  },
  {
    slug: 'computer-science-tutors',
    shortSlug: 'computer-science',
    category: 'STEM',
    name: 'Computer Science',
    titleSubject: 'Computer Science Tutors',
    searchTerm: 'Computer Science',
    description: 'programming, debugging, data structures, algorithms, discrete math, projects, and technical coursework',
    keywords: ['computer science tutor', 'CS tutor', 'programming tutor', 'data structures tutor', 'algorithms tutor'],
    painPoints: ['debugging frustration', 'abstract algorithms', 'project deadlines', 'syntax and logic gaps'],
    relatedSubjects: ['data-science-tutors', 'calculus-tutors', 'statistics-tutors', 'engineering-tutors'],
    tutoringCopy: 'Computer science tutoring helps students debug, reason through code, and understand the concepts behind assignments. Ask Marketplace supports programming, data structures, algorithms, discrete math, projects, and technical coursework.',
    painPointCopy: 'CS assignments can stall for hours because one bug or unclear concept blocks everything else. A tutor can help students reason through the issue and build better debugging habits.',
    faqs: [
      ['What can a computer science tutor help with?', 'Computer science tutors can help with programming, debugging, data structures, algorithms, discrete math, project planning, and code review.'],
      ['Can tutors help without doing the assignment for me?', 'Yes. Good CS tutoring focuses on explaining concepts, debugging approach, and helping students write and understand their own code.'],
      ['What languages can CS tutors support?', 'Support depends on the tutor, but common languages include Python, Java, JavaScript, C++, and course-specific languages.'],
    ],
  },
  {
    slug: 'engineering-tutors',
    shortSlug: 'engineering',
    category: 'STEM',
    name: 'Engineering',
    titleSubject: 'Engineering Tutors',
    searchTerm: 'Engineering',
    description: 'engineering math, physics, mechanics, circuits, problem sets, design projects, and technical exams',
    keywords: ['engineering tutor', 'college engineering tutoring', 'engineering math tutor', 'mechanics tutor', 'circuits tutor'],
    painPoints: ['long problem sets', 'technical prerequisites', 'project workload', 'multi-step exams'],
    relatedSubjects: ['physics-tutors', 'calculus-tutors', 'computer-science-tutors', 'data-science-tutors'],
    tutoringCopy: 'Engineering tutoring helps students manage technical problem sets, prerequisite gaps, and project-heavy classes. Ask Marketplace supports engineering math, physics, mechanics, circuits, design projects, and exam prep.',
    painPointCopy: 'Engineering courses often require students to combine math, physics, software, and design thinking in one assignment. A tutor can help break the work into clearer steps.',
    faqs: [
      ['What can an engineering tutor help with?', 'Engineering tutors can help with engineering math, mechanics, circuits, physics applications, technical problem sets, and project planning.'],
      ['Can engineering tutoring help with problem sets?', 'Yes. Tutors can help students understand setup, methods, and mistakes while keeping the submitted work their own.'],
      ['Is engineering tutoring useful for first-year students?', 'Yes. Early engineering courses often move quickly and depend on calculus, physics, and programming foundations.'],
    ],
  },
  {
    slug: 'data-science-tutors',
    shortSlug: 'data-science',
    category: 'STEM',
    name: 'Data Science',
    titleSubject: 'Data Science Tutors',
    searchTerm: 'Data Science',
    description: 'Python, R, statistics, machine learning basics, data cleaning, visualization, and analytics projects',
    keywords: ['data science tutor', 'college data science tutoring', 'Python data tutor', 'machine learning tutor', 'analytics tutor'],
    painPoints: ['messy datasets', 'coding errors', 'stats interpretation', 'project scope'],
    relatedSubjects: ['computer-science-tutors', 'statistics-tutors', 'economics-tutors', 'calculus-tutors'],
    tutoringCopy: 'Data science tutoring helps students connect code, statistics, and real datasets. Ask Marketplace supports Python, R, data cleaning, visualization, regression, machine learning basics, and analytics projects.',
    painPointCopy: 'Data science assignments can be confusing because errors may come from code, data, or statistics. A tutor can help students isolate the issue and explain results clearly.',
    faqs: [
      ['What can a data science tutor help with?', 'Data science tutors can help with Python, R, data cleaning, visualization, statistics, regression, machine learning basics, and analytics projects.'],
      ['Can data science tutoring help with projects?', 'Yes. Tutors can help students scope a project, debug code, interpret outputs, and communicate findings.'],
      ['Is data science tutoring connected to CS and statistics?', 'Yes. Data science often blends computer science, statistics, math, and domain-specific analysis.'],
    ],
  },
  {
    slug: 'finance-tutors',
    shortSlug: 'finance',
    category: 'Business',
    name: 'Finance',
    titleSubject: 'Finance Tutors',
    searchTerm: 'Finance',
    description: 'corporate finance, investments, valuation, Excel modeling, capital markets, and finance problem sets',
    keywords: ['finance tutor', 'college finance tutoring', 'corporate finance tutor', 'investments tutor', 'valuation tutor'],
    painPoints: ['formula-heavy exams', 'Excel modeling', 'valuation logic', 'technical interview pressure'],
    relatedSubjects: ['accounting-tutors', 'economics-tutors', 'statistics-tutors', 'data-science-tutors'],
    tutoringCopy: 'Finance tutoring works best when students can slow down the formulas, connect concepts to real cases, and practice the exact style of problems they see in class. Ask Marketplace helps students find tutors for corporate finance, investments, valuation, Excel modeling, and exam review.',
    painPointCopy: 'Finance classes often combine theory, calculator work, spreadsheets, and fast exam pacing. A tutor can help turn confusing lecture notes into a practical study plan with targeted practice.',
    faqs: [
      ['What can a finance tutor help with?', 'A finance tutor can help with time value of money, valuation, investments, capital budgeting, Excel models, homework review, and exam preparation.'],
      ['Is finance tutoring useful for business school classes?', 'Yes. Finance tutoring is especially useful for business school core classes, upper-level electives, and students preparing for internship technical questions.'],
      ['Can I find online finance tutoring?', 'Tutor listings can support online, in-person, or hybrid sessions depending on the tutor availability.'],
    ],
  },
  {
    slug: 'accounting-tutors',
    shortSlug: 'accounting',
    category: 'Business',
    name: 'Accounting',
    titleSubject: 'Accounting Tutors',
    searchTerm: 'Accounting',
    description: 'financial accounting, managerial accounting, journal entries, debits and credits, statements, and exam review',
    keywords: ['accounting tutor', 'college accounting tutoring', 'financial accounting tutor', 'managerial accounting tutor', 'debits and credits help'],
    painPoints: ['debits and credits', 'multi-step statements', 'cumulative exams', 'business prerequisite pressure'],
    relatedSubjects: ['finance-tutors', 'economics-tutors', 'statistics-tutors', 'writing-tutors'],
    tutoringCopy: 'Accounting tutoring helps students build the foundation that later business courses rely on. Ask Marketplace connects students with help for journal entries, financial statements, managerial accounting, cost concepts, homework review, and test prep.',
    painPointCopy: 'Accounting can feel unforgiving because one missed concept can make an entire problem fall apart. A tutor can help students practice step by step until the logic becomes repeatable.',
    faqs: [
      ['What topics can an accounting tutor cover?', 'Accounting tutors can help with debits and credits, journal entries, adjusting entries, financial statements, managerial accounting, cost accounting, and exam review.'],
      ['Can tutoring help with introductory accounting?', 'Yes. Intro accounting is one of the most common tutoring needs because the course introduces a new way of thinking about transactions and statements.'],
      ['Can I get help before an accounting exam?', 'Yes. Tutors can review weak areas, walk through practice problems, and help organize a focused exam prep plan.'],
    ],
  },
  {
    slug: 'economics-tutors',
    shortSlug: 'economics',
    category: 'Business',
    name: 'Economics',
    titleSubject: 'Economics Tutors',
    searchTerm: 'Economics',
    description: 'microeconomics, macroeconomics, graphs, models, problem sets, and quantitative economic reasoning',
    keywords: ['economics tutor', 'college economics tutoring', 'microeconomics tutor', 'macroeconomics tutor', 'economics graphs help'],
    painPoints: ['graph interpretation', 'abstract models', 'quantitative problem sets', 'written explanations'],
    relatedSubjects: ['statistics-tutors', 'finance-tutors', 'political-science-tutors', 'data-science-tutors'],
    tutoringCopy: 'Economics tutoring helps students connect graphs, formulas, models, and written explanations. Ask Marketplace supports microeconomics, macroeconomics, intermediate theory, quantitative problem sets, and exam prep.',
    painPointCopy: 'Economics classes often move between intuition and math quickly. A tutor can help students understand what the model means before they memorize the answer pattern.',
    faqs: [
      ['What does an economics tutor help with?', 'Economics tutors can help with supply and demand, elasticity, consumer theory, producer theory, macro models, graphs, and quantitative problem sets.'],
      ['Can tutoring help with economics graphs?', 'Yes. Tutors can help students understand how to read, draw, shift, and explain economics graphs clearly.'],
      ['Is economics tutoring only for majors?', 'No. Tutoring can help majors, business students, and students taking economics as a requirement.'],
    ],
  },
  {
    slug: 'psychology-tutors',
    shortSlug: 'psychology',
    category: 'Humanities',
    name: 'Psychology',
    titleSubject: 'Psychology Tutors',
    searchTerm: 'Psychology',
    description: 'intro psychology, research methods, biopsychology, cognitive psychology, statistics, and papers',
    keywords: ['psychology tutor', 'college psychology tutoring', 'intro psychology tutor', 'research methods tutor', 'psychology statistics help'],
    painPoints: ['research methods', 'terminology', 'statistics requirements', 'paper structure'],
    relatedSubjects: ['statistics-tutors', 'biology-tutors', 'writing-tutors', 'political-science-tutors'],
    tutoringCopy: 'Psychology tutoring helps students connect theories, research methods, experiments, and written assignments. Ask Marketplace supports intro psychology, biopsychology, cognitive psychology, research methods, statistics, and papers.',
    painPointCopy: 'Psychology courses can shift between memorization, research design, statistics, and writing. A tutor can help students understand what each assignment is really testing.',
    faqs: [
      ['What can a psychology tutor help with?', 'Psychology tutors can help with terminology, theories, research methods, biopsychology, cognitive psychology, statistics, and papers.'],
      ['Can psychology tutoring help with research methods?', 'Yes. Tutors can help students understand variables, study design, data interpretation, and written research explanations.'],
      ['Is psychology tutoring useful for papers?', 'Yes. Tutors can help with outlines, argument clarity, source integration, and revision planning.'],
    ],
  },
  {
    slug: 'writing-tutors',
    shortSlug: 'writing',
    category: 'Humanities',
    name: 'Writing',
    titleSubject: 'Writing Tutors',
    searchTerm: 'Writing',
    description: 'essays, research papers, outlines, thesis development, citations, revisions, and writing assignments',
    keywords: ['writing tutor', 'college writing tutoring', 'essay tutor', 'research paper tutor', 'college paper help'],
    painPoints: ['unclear prompts', 'thesis development', 'source integration', 'revision deadlines'],
    relatedSubjects: ['history-tutors', 'political-science-tutors', 'psychology-tutors', 'economics-tutors'],
    tutoringCopy: 'Writing tutoring helps students turn ideas into clear, organized papers. Ask Marketplace supports outlines, thesis development, research papers, citations, revision, class essays, and writing-heavy assignments.',
    painPointCopy: 'College writing can be hard because the assignment is often broad and feedback arrives late. A tutor can help students clarify the argument, structure the paper, and revise with purpose.',
    faqs: [
      ['What can a writing tutor help with?', 'Writing tutors can help with brainstorming, outlines, thesis statements, essay structure, research papers, citations, editing, and revision planning.'],
      ['Will a writing tutor write my paper for me?', 'No. The goal is to help students improve their own work through feedback, structure, and revision support.'],
      ['Can writing tutoring help with non-English classes?', 'Yes. Writing support can help with papers in history, business, economics, humanities, social science, and other writing-heavy courses.'],
    ],
  },
  {
    slug: 'history-tutors',
    shortSlug: 'history',
    category: 'Humanities',
    name: 'History',
    titleSubject: 'History Tutors',
    searchTerm: 'History',
    description: 'reading-heavy courses, timelines, primary sources, essay arguments, research papers, and exam review',
    keywords: ['history tutor', 'college history tutoring', 'history essay tutor', 'primary source help', 'history exam prep'],
    painPoints: ['dense readings', 'timeline confusion', 'primary source analysis', 'essay organization'],
    relatedSubjects: ['writing-tutors', 'political-science-tutors', 'psychology-tutors', 'economics-tutors'],
    tutoringCopy: 'History tutoring helps students manage readings, connect events, analyze sources, and write stronger papers. Ask Marketplace supports timelines, primary sources, essay arguments, research papers, and exam review.',
    painPointCopy: 'History courses often require students to move from facts to argument. A tutor can help students organize evidence, understand context, and write clearer analysis.',
    faqs: [
      ['What can a history tutor help with?', 'History tutors can help with readings, timelines, primary sources, essay outlines, research papers, and exam review.'],
      ['Can history tutoring help with papers?', 'Yes. Tutors can help students build arguments, organize evidence, and revise structure while keeping the writing their own.'],
      ['Can tutors help with reading-heavy history classes?', 'Yes. Tutors can help students identify the main argument, context, and evidence in long readings.'],
    ],
  },
  {
    slug: 'political-science-tutors',
    shortSlug: 'political-science',
    category: 'Humanities',
    name: 'Political Science',
    titleSubject: 'Political Science Tutors',
    searchTerm: 'Political Science',
    description: 'political theory, comparative politics, American politics, international relations, research, and papers',
    keywords: ['political science tutor', 'college political science tutoring', 'political theory tutor', 'international relations tutor', 'poli sci paper help'],
    painPoints: ['theory-heavy readings', 'argument structure', 'research design', 'policy analysis'],
    relatedSubjects: ['history-tutors', 'writing-tutors', 'economics-tutors', 'statistics-tutors'],
    tutoringCopy: 'Political science tutoring helps students understand theories, institutions, policy arguments, and research assignments. Ask Marketplace supports political theory, comparative politics, American politics, international relations, research, and papers.',
    painPointCopy: 'Political science classes can be writing-heavy and concept-heavy at the same time. A tutor can help students clarify arguments, connect readings, and structure papers or exam responses.',
    faqs: [
      ['What can a political science tutor help with?', 'Political science tutors can help with theory, comparative politics, American politics, international relations, policy analysis, research, and papers.'],
      ['Can political science tutoring help with essays?', 'Yes. Tutors can help students develop a thesis, organize evidence, and revise arguments for clarity.'],
      ['Is statistics useful for political science?', 'Yes. Many political science courses use statistics, research methods, polling data, or quantitative policy analysis.'],
    ],
  },
];

export const schools = [
  {
    slug: 'nyu',
    name: 'NYU',
    fullName: 'New York University',
    location: 'New York, NY',
    description: 'NYU students balance demanding classes, internships, clubs, and city life. Ask Marketplace helps students find peer tutoring for Stern, CAS, Tandon, and other NYU programs without wasting time searching group chats.',
    strengths: ['Stern business courses', 'economics', 'math', 'writing seminars', 'computer science', 'pre-health coursework'],
    painPoints: ['fast-paced quantitative classes', 'large lectures', 'internship-heavy schedules', 'midterm clustering'],
    keywords: ['NYU tutoring', 'NYU tutor', 'Stern finance tutor', 'NYU accounting tutor', 'NYU economics tutor'],
    faqs: [
      ['What subjects can NYU students find tutors for?', 'NYU students can look for help in accounting, finance, economics, math, writing, computer science, and exam prep.'],
      ['Is Ask Marketplace only for business classes at NYU?', 'No. Business tutoring is common, but the marketplace can support any class where students want peer help.'],
      ['Can NYU students become tutors?', 'Yes. Students who are strong in a course can create a listing and offer tutoring to classmates.'],
    ],
  },
  {
    slug: 'baruch',
    name: 'Baruch',
    fullName: 'Baruch College',
    location: 'New York, NY',
    description: 'Baruch students often need practical, focused tutoring for Zicklin business courses, accounting sequences, finance classes, economics, statistics, and writing-heavy requirements.',
    strengths: ['accounting', 'finance', 'economics', 'statistics', 'business writing', 'Excel'],
    painPoints: ['competitive business prerequisites', 'accounting sequence pressure', 'commuter schedules', 'evening study constraints'],
    keywords: ['Baruch tutoring', 'Baruch accounting tutor', 'Zicklin tutor', 'Baruch finance tutor'],
    faqs: [
      ['What tutoring is most useful for Baruch students?', 'Many Baruch students look for accounting, finance, economics, statistics, Excel, and writing help.'],
      ['Can tutors help with Zicklin prerequisites?', 'Yes. Peer tutors can support prerequisite review, homework practice, and exam preparation.'],
      ['Is online tutoring available for Baruch students?', 'Tutors can offer in-person, online, or hybrid sessions depending on their listing.'],
    ],
  },
  {
    slug: 'columbia',
    name: 'Columbia',
    fullName: 'Columbia University',
    location: 'New York, NY',
    description: 'Columbia students manage rigorous Core requirements, quantitative courses, writing demands, and major-specific workloads. Ask Marketplace helps them connect with tutors who understand intense academic pacing.',
    strengths: ['Core writing', 'economics', 'calculus', 'statistics', 'computer science', 'pre-med sciences'],
    painPoints: ['dense reading loads', 'proof-heavy math', 'research writing', 'competitive STEM classes'],
    keywords: ['Columbia tutoring', 'Columbia tutor', 'Columbia economics tutor', 'Columbia writing tutor'],
    faqs: [
      ['What Columbia classes can tutoring help with?', 'Tutoring can help with economics, math, statistics, writing, Core papers, computer science, and science prerequisites.'],
      ['Can Columbia tutors help with writing?', 'Yes. Writing support can include outlines, thesis clarity, structure, citation planning, and revision.'],
      ['How should Columbia students choose a tutor?', 'Students should look for subject fit, course familiarity, availability, and clear communication style.'],
    ],
  },
  {
    slug: 'cornell',
    name: 'Cornell',
    fullName: 'Cornell University',
    location: 'Ithaca, NY',
    description: 'Cornell courses can move quickly, especially in engineering, business, economics, math, and writing-heavy majors. Ask Marketplace gives students a direct way to find peer academic support.',
    strengths: ['engineering math', 'Dyson business courses', 'economics', 'statistics', 'writing', 'pre-med sciences'],
    painPoints: ['large STEM lectures', 'challenging prelims', 'problem set workload', 'major-specific grading pressure'],
    keywords: ['Cornell tutoring', 'Cornell tutor', 'Cornell economics tutor', 'Cornell math tutor'],
    faqs: [
      ['What makes Cornell tutoring different?', 'Cornell students often need help preparing for prelims, managing problem sets, and reviewing dense course material.'],
      ['Can tutoring help with Cornell prelims?', 'Yes. Tutors can help students organize review, practice problems, and clarify weak topics before prelims.'],
      ['Can Cornell students tutor other students?', 'Yes. Strong students can list tutoring services and offer sessions around their schedule.'],
    ],
  },
  {
    slug: 'michigan',
    name: 'Michigan',
    fullName: 'University of Michigan',
    location: 'Ann Arbor, MI',
    description: 'Michigan students across Ross, LSA, engineering, economics, math, and writing courses can use Ask Marketplace to find focused tutoring from peers who understand campus academics.',
    strengths: ['Ross business courses', 'economics', 'engineering math', 'statistics', 'writing', 'computer science'],
    painPoints: ['large lectures', 'competitive prerequisites', 'project-heavy courses', 'exam-heavy semesters'],
    keywords: ['Michigan tutoring', 'UMich tutor', 'Ross tutor', 'Michigan finance tutor'],
    faqs: [
      ['What subjects are common for Michigan tutoring?', 'Common subjects include finance, accounting, economics, math, statistics, writing, and computer science.'],
      ['Can Ross students find business tutors?', 'Yes. Tutors can list support for finance, accounting, Excel, business analytics, and related courses.'],
      ['Is Ask Marketplace useful outside Ross?', 'Yes. The school pages support broad academic tutoring, not only business classes.'],
    ],
  },
  {
    slug: 'ucla',
    name: 'UCLA',
    fullName: 'University of California, Los Angeles',
    location: 'Los Angeles, CA',
    description: 'UCLA students juggle competitive majors, STEM sequences, writing requirements, and packed schedules. Ask Marketplace helps students find tutoring for tough courses and exam prep.',
    strengths: ['economics', 'math', 'statistics', 'pre-med sciences', 'writing', 'business economics'],
    painPoints: ['impacted classes', 'large lectures', 'quarter-system pace', 'exam compression'],
    keywords: ['UCLA tutoring', 'UCLA tutor', 'UCLA economics tutor', 'UCLA math tutor'],
    faqs: [
      ['Why do UCLA students use tutoring?', 'The quarter system moves quickly, so tutoring can help students stay current and prepare before exams.'],
      ['What UCLA subjects fit Ask Marketplace?', 'Economics, math, statistics, writing, science prerequisites, and business economics are strong fits.'],
      ['Can tutors offer remote sessions?', 'Yes. Tutor listings can support online, in-person, or both.'],
    ],
  },
  {
    slug: 'usc',
    name: 'USC',
    fullName: 'University of Southern California',
    location: 'Los Angeles, CA',
    description: 'USC students in Marshall, Dornsife, Viterbi, and other programs can use Ask Marketplace for peer tutoring in business, quantitative courses, writing, and exam prep.',
    strengths: ['Marshall business courses', 'finance', 'accounting', 'economics', 'engineering math', 'writing'],
    painPoints: ['business prerequisites', 'networking and internship schedules', 'technical project load', 'exam preparation'],
    keywords: ['USC tutoring', 'USC tutor', 'Marshall finance tutor', 'USC accounting tutor'],
    faqs: [
      ['What USC programs are strong fits for tutoring?', 'Marshall business, Dornsife economics, Viterbi quantitative courses, writing, and exam prep are strong fits.'],
      ['Can USC students become tutors?', 'Yes. Students can create listings and offer subject-specific tutoring.'],
      ['Does Ask Marketplace support finance tutoring at USC?', 'Yes. Tutors can offer support in finance, accounting, valuation, Excel, and related coursework.'],
    ],
  },
  {
    slug: 'indiana',
    name: 'Indiana',
    fullName: 'Indiana University Bloomington',
    location: 'Bloomington, IN',
    description: 'Indiana students, especially those in Kelley and large prerequisite courses, can use Ask Marketplace to find tutoring for business, economics, math, writing, and exam prep.',
    strengths: ['Kelley business courses', 'accounting', 'finance', 'economics', 'statistics', 'writing'],
    painPoints: ['Kelley prerequisites', 'large intro classes', 'case and project work', 'exam-heavy weeks'],
    keywords: ['Indiana tutoring', 'IU tutor', 'Kelley tutor', 'Indiana accounting tutor'],
    faqs: [
      ['Can Kelley students find tutors?', 'Yes. Tutors can support accounting, finance, economics, statistics, and other business classes.'],
      ['What tutoring helps Indiana students most?', 'Focused help before exams, problem-set review, writing support, and business prerequisite support are common.'],
      ['Can IU students offer tutoring?', 'Yes. Students can list their tutoring services and availability.'],
    ],
  },
  {
    slug: 'ut-austin',
    name: 'UT Austin',
    fullName: 'The University of Texas at Austin',
    location: 'Austin, TX',
    description: 'UT Austin students in McCombs, engineering, economics, math, and writing-intensive courses can use Ask Marketplace to find practical academic support.',
    strengths: ['McCombs business courses', 'finance', 'accounting', 'engineering math', 'economics', 'writing'],
    painPoints: ['competitive majors', 'large lectures', 'technical coursework', 'exam and project overlap'],
    keywords: ['UT Austin tutoring', 'UT tutor', 'McCombs tutor', 'UT Austin finance tutor'],
    faqs: [
      ['What UT Austin subjects can tutors support?', 'Tutors can support finance, accounting, economics, math, writing, statistics, and engineering prerequisites.'],
      ['Is Ask Marketplace only for McCombs?', 'No. McCombs is a strong fit, but the platform supports students across majors.'],
      ['Can UT Austin students book tutoring quickly?', 'Students can browse listings, compare subjects, and book based on tutor availability.'],
    ],
  },
  {
    slug: 'rutgers',
    name: 'Rutgers',
    fullName: 'Rutgers University',
    location: 'New Brunswick, NJ',
    description: 'Rutgers students across business, economics, STEM, writing, and large prerequisite courses can use Ask Marketplace to find peer tutoring that fits their schedule.',
    strengths: ['business courses', 'accounting', 'finance', 'economics', 'statistics', 'writing'],
    painPoints: ['multi-campus schedules', 'large lectures', 'commuting between classes', 'exam-heavy prerequisites'],
    keywords: ['Rutgers tutoring', 'Rutgers tutor', 'Rutgers accounting tutor', 'Rutgers finance tutor'],
    faqs: [
      ['What Rutgers tutoring subjects are supported?', 'Accounting, finance, economics, math, statistics, writing, and exam prep are all strong fits.'],
      ['Can Rutgers students find tutors by subject?', 'Yes. School pages connect students to subject-focused tutoring paths.'],
      ['Can Rutgers students become tutors?', 'Yes. Students can create listings and offer help in courses they know well.'],
    ],
  },
  {
    slug: 'northeastern',
    name: 'Northeastern',
    fullName: 'Northeastern University',
    location: 'Boston, MA',
    description: 'Northeastern students often balance co-ops, classes, and project work. Ask Marketplace helps them find tutoring for business, economics, math, writing, and technical courses.',
    strengths: ['D’Amore-McKim business courses', 'finance', 'accounting', 'economics', 'computer science', 'writing'],
    painPoints: ['co-op schedule conflicts', 'project-based classes', 'fast semesters', 'quantitative prerequisites'],
    keywords: ['Northeastern tutoring', 'Northeastern tutor', 'D’Amore-McKim tutor', 'Northeastern finance tutor'],
    faqs: [
      ['Why is tutoring useful for Northeastern students?', 'Co-op and class schedules can be demanding, so focused peer help can keep coursework manageable.'],
      ['What Northeastern subjects fit Ask Marketplace?', 'Business, accounting, finance, economics, math, writing, and computer science all fit well.'],
      ['Can tutoring work around co-op schedules?', 'Tutors can set availability that works for evenings, weekends, or remote sessions.'],
    ],
  },
  {
    slug: 'bu',
    name: 'BU',
    fullName: 'Boston University',
    location: 'Boston, MA',
    description: 'BU students in Questrom, CAS, engineering, communications, and writing-heavy courses can use Ask Marketplace to find tutors for challenging classes and exam prep.',
    strengths: ['Questrom business courses', 'finance', 'accounting', 'economics', 'statistics', 'writing'],
    painPoints: ['large courses', 'business core workload', 'writing requirements', 'exam clusters'],
    keywords: ['BU tutoring', 'Boston University tutor', 'Questrom tutor', 'BU finance tutor'],
    faqs: [
      ['What BU programs are strong fits for tutoring?', 'Questrom business, economics, statistics, writing, math, and exam prep are strong fits.'],
      ['Can BU students offer peer tutoring?', 'Yes. Students can create tutor listings and accept bookings.'],
      ['Does Ask Marketplace support writing help at BU?', 'Yes. Tutors can help with structure, outlines, research papers, and revision.'],
    ],
  },
  {
    slug: 'uf',
    name: 'UF',
    fullName: 'University of Florida',
    location: 'Gainesville, FL',
    description: 'UF students across business, economics, STEM, writing, and exam-heavy majors can use Ask Marketplace to connect with peer tutors who understand college coursework.',
    strengths: ['Warrington business courses', 'accounting', 'finance', 'economics', 'math', 'pre-health sciences'],
    painPoints: ['large lectures', 'competitive prerequisites', 'STEM sequences', 'exam-heavy semesters'],
    keywords: ['UF tutoring', 'University of Florida tutor', 'UF accounting tutor', 'UF finance tutor'],
    faqs: [
      ['What UF subjects can tutors help with?', 'Tutors can support accounting, finance, economics, math, writing, science prerequisites, and exam prep.'],
      ['Can Warrington students find tutoring?', 'Yes. Business subjects like finance, accounting, and economics are core marketplace use cases.'],
      ['Can UF students become tutors?', 'Yes. Students can create listings and help peers in courses they know well.'],
    ],
  },
  {
    slug: 'fsu',
    name: 'FSU',
    fullName: 'Florida State University',
    location: 'Tallahassee, FL',
    description: 'FSU students in business, economics, math, writing, and science prerequisites can use Ask Marketplace to find focused tutoring and exam prep support.',
    strengths: ['business courses', 'finance', 'accounting', 'economics', 'statistics', 'writing'],
    painPoints: ['large classes', 'business prerequisites', 'exam prep pressure', 'writing-heavy requirements'],
    keywords: ['FSU tutoring', 'Florida State tutor', 'FSU accounting tutor', 'FSU finance tutor'],
    faqs: [
      ['What FSU subjects are best for tutoring?', 'Accounting, finance, economics, math, statistics, writing, and exam prep are strong fits.'],
      ['Can FSU students tutor other students?', 'Yes. Students can list subjects, availability, and session type.'],
      ['How can tutoring help before exams?', 'Tutors can review problem areas, organize practice, and help students focus study time.'],
    ],
  },
  {
    slug: 'yeshiva-university',
    name: 'Yeshiva University',
    fullName: 'Yeshiva University',
    location: 'New York, NY',
    description: 'Yeshiva University students can use Ask Marketplace to find trusted peer tutoring for Sy Syms business courses, accounting, finance, economics, math, writing, and exam prep.',
    strengths: ['Sy Syms business courses', 'accounting', 'finance', 'economics', 'math', 'writing'],
    painPoints: ['dual curriculum schedules', 'business prerequisites', 'tight exam windows', 'commuter and campus scheduling'],
    keywords: ['Yeshiva University tutoring', 'YU tutor', 'Sy Syms tutor', 'YU accounting tutor', 'YU finance tutor'],
    faqs: [
      ['How do Yeshiva University students find tutors on Ask Marketplace?', 'Students can browse tutors by subject, compare profiles, and book help for accounting, finance, economics, math, writing, and exam prep.'],
      ['Can YU students offer tutoring on Ask Marketplace?', 'Yes. Students who are strong in a subject can create a tutor listing and share availability for other students to book.'],
      ['What subjects are available for Yeshiva University tutoring?', 'Ask Marketplace supports tutoring for accounting, finance, economics, math, writing, exam prep, and other college courses.'],
    ],
  },
];

export function getSchoolBySlug(slug) {
  return schools.find((school) => school.slug === slug);
}

export function getSchoolSeoSubjectBySlug(slug) {
  return schoolSeoSubjects.find((subject) => subject.slug === slug);
}

export function schoolUrl(slug) {
  return `/schools/${slug}`;
}

export function schoolSubjectUrl(schoolSlug, subjectSlug) {
  return `/schools/${schoolSlug}/${subjectSlug}`;
}

export function subjectUrl(subjectSlug) {
  return `/subjects/${subjectSlug}`;
}

export function schoolSubjectUrls() {
  return schools.flatMap((school) =>
    schoolSeoSubjects.map((subject) => schoolSubjectUrl(school.slug, subject.slug))
  );
}

export function subjectUrls() {
  return schoolSeoSubjects.map((subject) => subjectUrl(subject.slug));
}
