/**
 * University data for programmatic SEO page generation.
 * Each entry generates a /schools/{slug}/ campus services landing page.
 */
export const universities = [
  // ── New York City ──────────────────────────────────────────────────────────
  { slug: 'yeshiva-university',   name: 'Yeshiva University', short: 'YU',      city: 'New York',      state: 'NY', strengths: ['finance','accounting','biology','pre-med','Jewish studies','Torah'] },
  { slug: 'nyu',                  name: 'NYU',                 short: 'NYU',     city: 'New York',      state: 'NY', strengths: ['finance','business','film','computer science','economics','pre-law'] },
  { slug: 'columbia',             name: 'Columbia University', short: 'Columbia',city: 'New York',      state: 'NY', strengths: ['pre-med','engineering','economics','political science','writing'] },
  { slug: 'fordham',              name: 'Fordham University',  short: 'Fordham', city: 'New York',      state: 'NY', strengths: ['business','law','psychology','accounting','finance'] },
  { slug: 'baruch',               name: 'Baruch College',      short: 'Baruch',  city: 'New York',      state: 'NY', strengths: ['accounting','finance','marketing','statistics','economics'] },
  { slug: 'hunter',               name: 'Hunter College',      short: 'Hunter',  city: 'New York',      state: 'NY', strengths: ['nursing','biology','psychology','social work','health sciences'] },
  { slug: 'brooklyn-college',     name: 'Brooklyn College',    short: 'BC',      city: 'Brooklyn',      state: 'NY', strengths: ['accounting','computer science','education','business'] },
  { slug: 'city-college-ny',      name: 'City College of NY',  short: 'CCNY',    city: 'New York',      state: 'NY', strengths: ['engineering','architecture','computer science','biomedical'] },
  { slug: 'queens-college',       name: 'Queens College',      short: 'QC',      city: 'Queens',        state: 'NY', strengths: ['accounting','music','education','psychology','business'] },
  { slug: 'stjohns',              name: "St. John's University",short: "St. John's",city:'Queens',       state: 'NY', strengths: ['pharmacy','law','business','accounting','criminal justice'] },
  { slug: 'pace',                 name: 'Pace University',     short: 'Pace',    city: 'New York',      state: 'NY', strengths: ['business','accounting','nursing','computer science','pre-law'] },
  { slug: 'new-school',           name: 'The New School',      short: 'TNS',     city: 'New York',      state: 'NY', strengths: ['design','liberal arts','social research','media','music'] },
  { slug: 'touro',                name: 'Touro University',    short: 'Touro',   city: 'New York',      state: 'NY', strengths: ['pre-med','health sciences','law','business','Jewish studies'] },
  { slug: 'lip',                  name: 'Long Island University', short:'LIU',   city: 'Brooklyn',      state: 'NY', strengths: ['pharmacy','health sciences','business','criminal justice'] },
  { slug: 'cooper-union',         name: 'Cooper Union',        short: 'Cooper',  city: 'New York',      state: 'NY', strengths: ['engineering','architecture','art','physics','math'] },
  // ── Greater New York / Tri-State ───────────────────────────────────────────
  { slug: 'hofstra',              name: 'Hofstra University',  short: 'Hofstra', city: 'Hempstead',     state: 'NY', strengths: ['business','law','journalism','health professions','finance'] },
  { slug: 'adelphi',              name: 'Adelphi University',  short: 'Adelphi', city: 'Garden City',   state: 'NY', strengths: ['nursing','social work','business','accounting','psychology'] },
  { slug: 'stony-brook',          name: 'Stony Brook University', short:'SBU',   city: 'Stony Brook',   state: 'NY', strengths: ['pre-med','engineering','computer science','biology','chemistry'] },
  { slug: 'binghamton',           name: 'Binghamton University', short:'Bing',   city: 'Binghamton',    state: 'NY', strengths: ['business','accounting','engineering','pre-med','CS'] },
  { slug: 'buffalo',              name: 'University at Buffalo', short:'UB',     city: 'Buffalo',       state: 'NY', strengths: ['engineering','pharmacy','architecture','business','pre-law'] },
  { slug: 'cornell',              name: 'Cornell University',  short:'Cornell',  city: 'Ithaca',        state: 'NY', strengths: ['engineering','pre-med','business','CS','agriculture','law'] },
  { slug: 'rpi',                  name: 'Rensselaer Polytechnic', short:'RPI',   city: 'Troy',          state: 'NY', strengths: ['engineering','CS','physics','architecture','biology'] },
  { slug: 'rit',                  name: 'Rochester Institute of Technology', short:'RIT', city:'Rochester', state:'NY', strengths:['CS','engineering','graphic design','business IT','photography'] },
  { slug: 'syracuse',             name: 'Syracuse University', short:'Syracuse', city: 'Syracuse',      state: 'NY', strengths: ['communications','law','business','architecture','information studies'] },
  { slug: 'rutgers',              name: 'Rutgers University',  short:'Rutgers',  city: 'New Brunswick', state: 'NJ', strengths: ['business','pharmacy','pre-med','engineering','CS'] },
  { slug: 'princeton',            name: 'Princeton University', short:'Princeton',city:'Princeton',      state: 'NJ', strengths: ['engineering','economics','CS','political science','math'] },
  { slug: 'seton-hall',           name: 'Seton Hall University',short:'SHU',     city: 'South Orange',  state: 'NJ', strengths: ['business','nursing','law','accounting','diplomacy'] },
  { slug: 'njit',                 name: 'NJIT',                short:'NJIT',     city: 'Newark',        state: 'NJ', strengths: ['engineering','architecture','CS','science','business'] },
  // ── New England ────────────────────────────────────────────────────────────
  { slug: 'harvard',              name: 'Harvard University',  short:'Harvard',  city: 'Cambridge',     state: 'MA', strengths: ['law','business','pre-med','economics','CS','government'] },
  { slug: 'mit',                  name: 'MIT',                 short:'MIT',      city: 'Cambridge',     state: 'MA', strengths: ['engineering','CS','physics','math','economics','architecture'] },
  { slug: 'boston-university',    name: 'Boston University',   short:'BU',       city: 'Boston',        state: 'MA', strengths: ['business','pre-med','communications','engineering','law'] },
  { slug: 'northeastern',         name: 'Northeastern University', short:'NEU',  city: 'Boston',        state: 'MA', strengths: ['CS','engineering','business','health sciences','data science'] },
  { slug: 'tufts',                name: 'Tufts University',    short:'Tufts',    city: 'Medford',       state: 'MA', strengths: ['pre-med','engineering','international relations','biology','CS'] },
  { slug: 'boston-college',       name: 'Boston College',      short:'BC',       city: 'Chestnut Hill', state: 'MA', strengths: ['finance','accounting','pre-law','biology','education'] },
  { slug: 'yale',                 name: 'Yale University',     short:'Yale',     city: 'New Haven',     state: 'CT', strengths: ['pre-law','medicine','history','political science','economics'] },
  { slug: 'brown',                name: 'Brown University',    short:'Brown',    city: 'Providence',    state: 'RI', strengths: ['pre-med','CS','economics','cognitive neuroscience','writing'] },
  { slug: 'dartmouth',            name: 'Dartmouth College',   short:'Dartmouth',city: 'Hanover',       state: 'NH', strengths: ['business','medicine','engineering','economics','public policy'] },
  { slug: 'umass-amherst',        name: 'UMass Amherst',       short:'UMass',    city: 'Amherst',       state: 'MA', strengths: ['engineering','CS','business','pre-med','education'] },
  { slug: 'uconn',                name: 'University of Connecticut', short:'UConn', city:'Storrs',       state: 'CT', strengths: ['business','engineering','pre-law','nursing','pharmacy'] },
  // ── Mid-Atlantic ───────────────────────────────────────────────────────────
  { slug: 'upenn',                name: 'University of Pennsylvania', short:'Penn', city:'Philadelphia', state: 'PA', strengths: ['business','pre-med','law','engineering','nursing'] },
  { slug: 'drexel',               name: 'Drexel University',   short:'Drexel',   city: 'Philadelphia',  state: 'PA', strengths: ['engineering','CS','design','business','nursing'] },
  { slug: 'temple',               name: 'Temple University',   short:'Temple',   city: 'Philadelphia',  state: 'PA', strengths: ['business','law','communications','pre-med','accounting'] },
  { slug: 'georgetown',           name: 'Georgetown University', short:'Georgetown', city:'Washington',  state: 'DC', strengths: ['pre-law','government','business','international affairs','medicine'] },
  { slug: 'gwu',                  name: 'George Washington University', short:'GWU', city:'Washington', state: 'DC', strengths: ['pre-law','business','public health','international affairs','engineering'] },
  { slug: 'american-university',  name: 'American University', short:'AU',       city: 'Washington',    state: 'DC', strengths: ['pre-law','international studies','business','communications','public affairs'] },
  { slug: 'johns-hopkins',        name: 'Johns Hopkins University', short:'JHU', city: 'Baltimore',     state: 'MD', strengths: ['pre-med','biomedical engineering','public health','CS','international studies'] },
  { slug: 'umd',                  name: 'University of Maryland', short:'UMD',   city: 'College Park',  state: 'MD', strengths: ['CS','engineering','business','journalism','pre-med'] },
  { slug: 'carnegie-mellon',       name: 'Carnegie Mellon University', short:'CMU', city:'Pittsburgh',  state: 'PA', strengths: ['CS','engineering','design','business','drama'] },
  { slug: 'pitt',                 name: 'University of Pittsburgh', short:'Pitt', city: 'Pittsburgh',   state: 'PA', strengths: ['pre-med','business','engineering','public health','CS'] },
  // ── Southeast ──────────────────────────────────────────────────────────────
  { slug: 'duke',                 name: 'Duke University',     short:'Duke',     city: 'Durham',        state: 'NC', strengths: ['pre-med','law','business','engineering','public policy'] },
  { slug: 'unc',                  name: 'UNC Chapel Hill',     short:'UNC',      city: 'Chapel Hill',   state: 'NC', strengths: ['business','pre-med','law','journalism','public health'] },
  { slug: 'wake-forest',          name: 'Wake Forest University', short:'WFU',   city: 'Winston-Salem', state: 'NC', strengths: ['business','pre-med','law','accounting','politics'] },
  { slug: 'emory',                name: 'Emory University',    short:'Emory',    city: 'Atlanta',       state: 'GA', strengths: ['pre-med','business','law','public health','nursing'] },
  { slug: 'georgia-tech',         name: 'Georgia Tech',        short:'GT',       city: 'Atlanta',       state: 'GA', strengths: ['engineering','CS','business','architecture','math'] },
  { slug: 'vanderbilt',           name: 'Vanderbilt University', short:'Vandy',  city: 'Nashville',     state: 'TN', strengths: ['pre-med','engineering','business','law','human and organizational development'] },
  { slug: 'florida',              name: 'University of Florida', short:'UF',     city: 'Gainesville',   state: 'FL', strengths: ['engineering','business','agriculture','pre-med','CS'] },
  { slug: 'fsu',                  name: 'Florida State University', short:'FSU', city: 'Tallahassee',   state: 'FL', strengths: ['business','criminology','pre-med','accounting','music'] },
  { slug: 'miami',                name: 'University of Miami', short:'UM',       city: 'Coral Gables',  state: 'FL', strengths: ['business','pre-med','law','marine science','music'] },
  { slug: 'ucf',                  name: 'University of Central Florida', short:'UCF', city:'Orlando',   state: 'FL', strengths: ['engineering','CS','hospitality','business','digital media'] },
  // ── Midwest ────────────────────────────────────────────────────────────────
  { slug: 'uchicago',             name: 'University of Chicago', short:'UChicago', city:'Chicago',      state: 'IL', strengths: ['economics','law','pre-med','statistics','CS'] },
  { slug: 'northwestern',         name: 'Northwestern University', short:'Northwestern', city:'Evanston', state:'IL', strengths:['journalism','business','pre-med','engineering','law'] },
  { slug: 'michigan',             name: 'University of Michigan', short:'UMich', city: 'Ann Arbor',     state: 'MI', strengths: ['engineering','business','pre-law','pre-med','CS'] },
  { slug: 'michigan-state',       name: 'Michigan State University', short:'MSU', city:'East Lansing',  state: 'MI', strengths: ['business','agriculture','pre-med','criminal justice','CS'] },
  { slug: 'ohio-state',           name: 'Ohio State University', short:'OSU',    city: 'Columbus',      state: 'OH', strengths: ['engineering','business','pre-med','education','law'] },
  { slug: 'indiana',              name: 'Indiana University',  short:'IU',       city: 'Bloomington',   state: 'IN', strengths: ['business','music','law','pre-med','journalism'] },
  { slug: 'purdue',               name: 'Purdue University',   short:'Purdue',   city: 'West Lafayette', state:'IN', strengths: ['engineering','CS','agriculture','pharmacy','aviation'] },
  { slug: 'notre-dame',           name: 'University of Notre Dame', short:'Notre Dame', city:'Notre Dame', state:'IN', strengths:['pre-law','business','pre-med','engineering','theology'] },
  { slug: 'umn',                  name: 'University of Minnesota', short:'UMN',  city: 'Minneapolis',   state: 'MN', strengths: ['engineering','pre-med','business','journalism','CS'] },
  { slug: 'wisconsin',            name: 'University of Wisconsin', short:'UW–Madison', city:'Madison',  state: 'WI', strengths: ['pre-med','engineering','business','journalism','CS'] },
  // ── South & Southwest ──────────────────────────────────────────────────────
  { slug: 'ut-austin',            name: 'UT Austin',           short:'UT',       city: 'Austin',        state: 'TX', strengths: ['engineering','CS','business','pre-law','communications'] },
  { slug: 'texas-am',             name: 'Texas A&M University', short:'A&M',     city: 'College Station', state:'TX', strengths: ['engineering','agriculture','CS','business','pre-med'] },
  { slug: 'smu',                  name: 'Southern Methodist University', short:'SMU', city:'Dallas',    state: 'TX', strengths: ['business','law','engineering','music','pre-med'] },
  { slug: 'rice',                 name: 'Rice University',     short:'Rice',     city: 'Houston',       state: 'TX', strengths: ['engineering','pre-med','CS','economics','music'] },
  { slug: 'tulane',               name: 'Tulane University',   short:'Tulane',   city: 'New Orleans',   state: 'LA', strengths: ['pre-med','business','law','public health','architecture'] },
  { slug: 'lsu',                  name: 'LSU',                 short:'LSU',      city: 'Baton Rouge',   state: 'LA', strengths: ['engineering','business','pre-med','agriculture','CS'] },
  { slug: 'alabama',              name: 'University of Alabama', short:'UA',     city: 'Tuscaloosa',    state: 'AL', strengths: ['business','pre-law','nursing','engineering','accounting'] },
  { slug: 'arizona',              name: 'University of Arizona', short:'UA',     city: 'Tucson',        state: 'AZ', strengths: ['pre-med','business','CS','engineering','astronomy'] },
  { slug: 'asu',                  name: 'Arizona State University', short:'ASU', city: 'Tempe',         state: 'AZ', strengths: ['engineering','CS','business','journalism','design'] },
  // ── West Coast ─────────────────────────────────────────────────────────────
  { slug: 'stanford',             name: 'Stanford University', short:'Stanford', city: 'Palo Alto',     state: 'CA', strengths: ['CS','engineering','business','pre-med','law','economics'] },
  { slug: 'berkeley',             name: 'UC Berkeley',         short:'Berkeley', city: 'Berkeley',      state: 'CA', strengths: ['CS','engineering','business','law','pre-med','economics'] },
  { slug: 'ucla',                 name: 'UCLA',                short:'UCLA',     city: 'Los Angeles',   state: 'CA', strengths: ['film','pre-med','engineering','CS','business','law'] },
  { slug: 'usc',                  name: 'USC',                 short:'USC',      city: 'Los Angeles',   state: 'CA', strengths: ['film','business','CS','engineering','communications','pre-med'] },
  { slug: 'ucsd',                 name: 'UC San Diego',        short:'UCSD',     city: 'San Diego',     state: 'CA', strengths: ['pre-med','engineering','CS','biology','economics'] },
  { slug: 'ucsb',                 name: 'UC Santa Barbara',    short:'UCSB',     city: 'Santa Barbara', state: 'CA', strengths: ['economics','CS','biology','environmental science','film'] },
  { slug: 'uci',                  name: 'UC Irvine',           short:'UCI',      city: 'Irvine',        state: 'CA', strengths: ['pre-med','CS','engineering','business','criminology'] },
  { slug: 'ucdavis',              name: 'UC Davis',            short:'UC Davis', city: 'Davis',         state: 'CA', strengths: ['agriculture','veterinary','pre-med','engineering','CS'] },
  { slug: 'caltech',              name: 'Caltech',             short:'Caltech',  city: 'Pasadena',      state: 'CA', strengths: ['engineering','physics','CS','math','chemistry'] },
  { slug: 'uw-seattle',           name: 'University of Washington', short:'UW', city: 'Seattle',        state: 'WA', strengths: ['CS','engineering','pre-med','business','nursing'] },
  { slug: 'oregon',               name: 'University of Oregon', short:'UO',     city: 'Eugene',        state: 'OR', strengths: ['business','journalism','architecture','design','pre-law'] },
  { slug: 'colorado',             name: 'University of Colorado', short:'CU',   city: 'Boulder',       state: 'CO', strengths: ['engineering','CS','business','pre-med','film'] },
  { slug: 'utah',                 name: 'University of Utah',  short:'U of U',  city: 'Salt Lake City', state:'UT', strengths: ['business','pre-med','CS','engineering','film'] },
];

export const allServices = [
  // Tutoring subjects
  { slug: 'tutors',           label: 'Tutors',                 search: '', category: 'tutor',   desc: 'Academic tutoring for every subject — math, science, business, humanities, and exam prep.' },
  { slug: 'math-tutors',      label: 'Math Tutors',            search: 'math', category: 'tutor', desc: 'Calculus, statistics, algebra, linear algebra, and quantitative reasoning tutoring.' },
  { slug: 'finance-tutors',   label: 'Finance Tutors',         search: 'finance', category: 'tutor', desc: 'Corporate finance, investments, valuation, financial modeling, and CFA prep.' },
  { slug: 'accounting-tutors',label: 'Accounting Tutors',      search: 'accounting', category: 'tutor', desc: 'Financial and managerial accounting, journal entries, CPA exam prep.' },
  { slug: 'chemistry-tutors', label: 'Chemistry Tutors',       search: 'chemistry', category: 'tutor', desc: 'General chemistry, organic chemistry, biochemistry, lab reports, and exams.' },
  { slug: 'biology-tutors',   label: 'Biology Tutors',         search: 'biology', category: 'tutor', desc: 'Cell biology, genetics, physiology, pre-med requirements, and lab coursework.' },
  { slug: 'cs-tutors',        label: 'CS / Coding Tutors',     search: 'computer science', category: 'tutor', desc: 'Python, Java, data structures, algorithms, web dev, and debugging help.' },
  { slug: 'economics-tutors', label: 'Economics Tutors',       search: 'economics', category: 'tutor', desc: 'Micro, macro, econometrics, game theory, and behavioral economics.' },
  { slug: 'writing-tutors',   label: 'Writing Tutors',         search: 'writing', category: 'tutor', desc: 'Essay feedback, research papers, citations, outlines, and argument structure.' },
  { slug: 'physics-tutors',   label: 'Physics Tutors',         search: 'physics', category: 'tutor', desc: 'Mechanics, E&M, thermodynamics, optics, modern physics, and problem sets.' },
  // Test prep
  { slug: 'mcat-prep',        label: 'MCAT Prep',              search: 'mcat', category: 'tutor',  desc: 'MCAT prep for all four sections — CARS, Bio/Biochem, Chem/Phys, Psych/Soc.' },
  { slug: 'lsat-prep',        label: 'LSAT Prep',              search: 'lsat', category: 'tutor',  desc: 'LSAT logical reasoning, analytical reasoning, reading comprehension, and full practice tests.' },
  { slug: 'gre-prep',         label: 'GRE Prep',               search: 'gre',  category: 'tutor',  desc: 'GRE quantitative, verbal, analytical writing, and full test strategy.' },
  { slug: 'gmat-prep',        label: 'GMAT Prep',              search: 'gmat', category: 'tutor',  desc: 'GMAT quant, verbal, integrated reasoning, and MBA application strategy.' },
  { slug: 'sat-act-prep',     label: 'SAT / ACT Prep',         search: 'sat',  category: 'tutor',  desc: 'SAT and ACT prep for math, reading, writing, and science reasoning.' },
  // Physical services
  { slug: 'barbers',          label: 'Barbers',                search: '', category: 'barber',  desc: 'Campus barbers — fades, tapers, beard trims, and haircuts by student barbers.' },
  { slug: 'personal-trainers',label: 'Personal Trainers',       search: '', category: 'fitness', desc: 'One-on-one fitness coaching — weight training, cardio, nutrition guidance, and sport-specific coaching.' },
  { slug: 'tennis-coaches',   label: 'Tennis Coaches',          search: 'tennis', category: 'fitness', desc: 'Private tennis lessons for all levels — groundstrokes, serve, volleys, match strategy.' },
  { slug: 'yoga-instructors', label: 'Yoga Instructors',        search: 'yoga',   category: 'fitness', desc: 'On-campus yoga instruction — Hatha, Vinyasa, restorative, and flexibility training.' },
  { slug: 'boxing-trainers',  label: 'Boxing Trainers',         search: 'boxing', category: 'fitness', desc: 'Boxing technique, bag work, footwork, conditioning, and self-defense fundamentals.' },
  // Music
  { slug: 'guitar-teachers',  label: 'Guitar Teachers',         search: 'guitar', category: 'music', desc: 'Acoustic, electric, and classical guitar for all levels, plus music theory.' },
  { slug: 'piano-teachers',   label: 'Piano Teachers',          search: 'piano',  category: 'music', desc: 'Classical, pop, jazz piano, sight-reading, and music theory lessons.' },
  // Languages
  { slug: 'hebrew-tutors',    label: 'Hebrew Tutors',           search: 'hebrew', category: 'languages', desc: 'Modern Ivrit and biblical Hebrew — reading, writing, grammar, and conversation.' },
  { slug: 'spanish-tutors',   label: 'Spanish Tutors',          search: 'spanish',category: 'languages', desc: 'Conversational Spanish, grammar, literature, DELE prep, and business Spanish.' },
  { slug: 'french-tutors',    label: 'French Tutors',           search: 'french', category: 'languages', desc: 'Conversational French, grammar, DELF prep, and French literature coursework.' },
  // Torah
  { slug: 'gemara-tutors',    label: 'Gemara Tutors',           search: 'gemara', category: 'Torah Studies', desc: 'Gemara learning, Rashi, Tosafot, and Halacha study partners and tutors.' },
];
